### ISSUE TITLE
Unexpected intermediate empty screen when opening notification

### ISSUE THREAD

**Issue by tomkad99** [Synerise/synerise-flutter-sdk#10]
We have updated library to 1.1.1 and trying to use approach with `Synerise.injector.listener(...)`.

The problem is when we launch method `NotificationsImpl.handleNotification(message)`, and after the click the intermediate empty screen with app name is shown:

<img width="409" alt="iShot_2024-06-24_15 50 56" src="https://github.com/Synerise/synerise-flutter-sdk/assets/81610280/6176ad4d-1113-4bfc-960e-89e896e80120">

After that the proper callback is correctly called

**Comment by konned** [comment]
Device? system version?

**Comment by tomkad99** [comment]
@konned I have reproduced that on both 

- Android 12.1 Oppo Reno 4 pro 5G
- Android 14.0 OnePlus Open


For me this looks like situation on all androids

**Comment by konned** [comment]
okay, we are investigating the problem.

**Comment by konned** [comment]
Have you tried configuring splash screen ? https://docs.flutter.dev/platform-integration/android/splash-screen ?

**Comment by tomkad99** [comment]
We have splash screen based on `flutter_native_splash`, I will check

**Comment by tomkad99** [comment]
@konned For a long time I tried to analyze our own MainActivity and I was not able to customize the behavior.

I have launched example project from 1.1.1 version and the problem is the same:

https://github.com/Synerise/synerise-flutter-sdk/assets/81610280/60695a04-34ca-4661-865d-16c230ead266

**Comment by konned** [comment]
We are working on that. It may be some lack of flags or intent actions in push notification click.

**Comment by tomkad99** [comment]
Thanks for support

**Comment by konned** [comment]
Do you have this problem on Android 11 and lower?

**Comment by tomkad99** [comment]
I will check today on Android 8

**Comment by tomkad99** [comment]
@konned On Samsung Galaxy J7 2016 with Android 8 I **DO NOT** see this white screen with toolbar

**Comment by konned** [comment]
Should be fixed on version 1.3.0 please check and let me know ;)

**Comment by tomkad99** [comment]
@konned Thank you for information, I will confirm that in few days.

**Comment by tomkad99** [comment]
After my checks I can confirm this problem has been resolved in all three states:

- Foreground
- Background
- Terminated

For URLs and deeplinks.

Thank you greately for your support.
