### ISSUE TITLE
Synerise notification's deeplink is handled only after resume

### ISSUE THREAD

**Issue by tmaxxdd** [Synerise/synerise-flutter-sdk#14]
During implementation of **sdk version 1.3.1**. We have noticed **on Andrioid** that there is a specific case when clicking on the notification **in foreground** the action is not invoked immediately but after resume (back from background)

The reproduction of error in example app:

https://github.com/user-attachments/assets/dca6924b-56be-4953-9f87-7a3427bbca1b

**Comment by konned** [comment]
Thanks, we are investigating this issue. I will let you know soon.

**Comment by tmaxxdd** [comment]
Thank you

**Comment by tmaxxdd** [comment]
@konned It is possible to estimate how long does it take to prepare a fix?

**Comment by konned** [comment]
We are in a final part of testing. Max 1-2 days to new release.

**Comment by tmaxxdd** [comment]
Thank you really much for the instant reply

**Comment by tmaxxdd** [comment]
Should we check the new 1.4.0 version?

**Comment by konned** [comment]
Yeap, Sorry I forgot to inform you yesterday.

**Comment by tmaxxdd** [comment]
Okay, I started implementing new version yesterday. Did you check the fix on the example app?

**Comment by tmaxxdd** [comment]
@konned I asked bc in our product using 1.4.0 this error still exists

**Comment by konned** [comment]
Yes, unfortunately we did not upgrade native sdk by a mistake. Version with a fix will be released during weekend.

**Comment by tmaxxdd** [comment]
Okay, thank you for response

**Comment by konned** [comment]
Hi, In 1.4.1 everything should work fine ;)

**Comment by tmaxxdd** [comment]
@konned We have no issues for now so I assume you can close this issue

**Comment by awoczek** [comment]
@tmaxxdd thank you for your feedback and help!
