### ISSUE TITLE
Library includes SoLoader library marked as potentially dangerous

### ISSUE THREAD

**Issue by tmaxxdd** [Synerise/synerise-flutter-sdk#15]
We have received information that our project includes outdated version of com.facebook.fresco:soloader library, but we are not implementing it our dependencies.

https://support.google.com/googleplay/android-developer/answer/12576726
![Screenshot 2024-09-27 at 10 40 12](https://github.com/user-attachments/assets/89f16a95-493b-4a58-80eb-f1fe6e9426da)

After creating the report this library is found in newest **1.3.1 version**:
[dependencies.txt](https://github.com/user-attachments/files/17163547/dependencies.txt)

**Comment by konned** [comment]
It will be fixed in a next release.

**Comment by tmaxxdd** [comment]
Thanks for quick reply :)
