### ISSUE TITLE
iOS SDK Version 4.23.2 Removed - Seeking alternative solution or update

### ISSUE THREAD

**Issue by carloschance** [Synerise/synerise-flutter-sdk#19]
I’ve noticed that iOS SDK version 4.23.2, which I was using, has been removed due to potential issues with background launch checks for UIScene and SwiftUI-based apps. The changelog for version 4.23.3 mentions this fix, but it seems the documentation in Flutter has not been updated to address this transition.

Could you provide guidance if there is an alternative solution or specific migration steps recommended for projects that were relying on 4.23.2?

**Comment by awoczek** [comment]
I'm sorry for this problem. We will provide Flutter SDK 1.4.3 on monday.

**Comment by carloschance** [comment]
@awoczek Just a quick note that Monday is a national holiday (Independence Day). Did you mean Tuesday?

**Comment by awoczek** [comment]
Yes, sorry for mistake.

**Comment by tmaxxdd** [comment]
We would be also really thankful for update today as it happened unfortunately just before our release :/

**Comment by awoczek** [comment]
There is 1.4.3 version available. Apologaise for your inconvinience.
