### ISSUE TITLE
Field in enum IdentityProvider should be named `identityProvider` instead of `identityPrvovider`

### ISSUE THREAD

**Issue by tomkadziolka** [Synerise/synerise-flutter-sdk#2]
Current version of library 0.6.3 contains typo.

<img width="403" alt="image" src="https://github.com/Synerise/synerise-flutter-sdk/assets/124564649/f800aebb-760c-455d-9757-4879b0a06d55">

**Comment by konned** [comment]
Hi,
Will be fixed in next release.

**Comment by tomkadziolka** [comment]
@konned Thanks :)

**Comment by soczowinski** [comment]
This typo has been fixed in the 0.7.1 version of the SDK
