### ISSUE TITLE
Extend description how to run an example

### ISSUE THREAD

**Issue by tomkadziolka** [Synerise/synerise-flutter-sdk#4]
Please add more details about launching example project:

First step is to replace value under `api_key.txt`

To make it work on Android device:
-  Replace file under android/app/google-services.json with own implementation

To make it work on iOS device:
- Replace file ios/Runner/GoogleService-Info.plist with own implementation

I have also a difficulty to launch the SampleAppFlutter target.

When I run regular `flutter run`, Then I have an error:

```
The Xcode project defines schemes: SampleAppFlutter, SyneriseCarouselNotificationContentExtension, SyneriseNotificationServiceExtension, SyneriseSingleMediaNotificationContentExtension
Exception: You must specify a --flavor option to select one of the available schemes.
```

When I run `flutter run --flavor=SampleAppFlutter` I got error:

```
The Xcode project defines build configurations: Debug, Debug copy, Release, Profile
Flutter expects a build configuration named Debug-SampleAppFlutter or similar.
Open Xcode to fix the problem:
  open ios/Runner.xcworkspace
1. Click on "Runner" in the project navigator.
2. Ensure the Runner PROJECT is selected, not the Runner TARGET.
3. Click the Editor->Add Configuration->Duplicate "Debug" Configuration.

   If this option is disabled, it is likely you have the target selected instead
   of the project; see:
   https://stackoverflow.com/questions/19842746/adding-a-build-configuration-in-xcode

   If you have created a completely custom set of build configurations,
   you can set the FLUTTER_BUILD_MODE=debug
   in the .xcconfig file for that configuration and run from Xcode.

4. If you are not using completely custom build configurations, name the newly created configuration debug.
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

The more information how to run it properly would be helpful :)

**Comment by tomkadziolka** [comment]
I created new Xcode configuration **Debug-SampleAppFlutter** and managed to start `flutter run` but I don't know if that is proper way of setting up the example.

**Comment by soczowinski** [comment]
Thank you for your suggestions, we will add more details to the installation guide in our documentation in future release, we are currently looking into the flavor issue.

**Comment by tmaxxdd** [comment]
@soczowinski Hello, has the example been corrected for this problem?

**Comment by ahnes86** [comment]
@tmaxxdd Not yet, it will be corrected with the next release this week.

**Comment by ahnes86** [comment]
@tmaxxdd please find changes in the latest release [0.8.0](https://github.com/Synerise/synerise-flutter-sdk/releases/tag/0.8.0)
