### ISSUE TITLE
Add `isSynerisePush` method for native push message source checking 

### ISSUE THREAD

**Issue by tomkadziolka** [Synerise/synerise-flutter-sdk#7]
Flutter SDK is missing important method to check the source of push notification

It would be great to have official method as for the other platforms:
https://help.synerise.com/developers/mobile-sdk/method-reference/android/campaigns/#check-if-push-notification-is-from-synerise.

Currently we base on our own `issuer` checking but this silly and not future proof.

**Comment by soczowinski** [comment]
This feature will be involved in the next version of the SDK.

**Comment by tomkadziolka** [comment]
@soczowinski Thank you for that information :)

**Comment by soczowinski** [comment]
The feature has been added in the 0.7.1 version of the SDK

[Link to method documentation in Help Center](https://hub.synerise.com/developers/mobile-sdk/method-reference/flutter/campaigns/#check-if-push-notification-is-from-synerise)
